### ISSUE TITLE
Validate information obtained by user during signup process

### ISSUE THREAD

**Issue by Talal-A** [Talal-A/calm-stop#19]
- [x] Create a single verification class accessible by both Officer and Citizen with _static_ functions.
- [x] Fully unit-test the verification class.

Current bugs: 
- [x] "Password must contain at least a letter and a number" -> 123456 passes
- [x]  "Driver license must be a letter followed by 8 numbers" - > 123456789 passes
- [x] Date of birth -> 22-33-2555 passes

**Comment by HowardTingling** [comment]
Address is no longer an input requirement; will remove them by tonight.
